GET http://localhost:3000/employees
###
GET http://localhost:3000/employees/5
###

GET http://localhost:3000/employees/count

###

POST http://localhost:3000/employees
Content-Type: application/json

{
    "LastName": "Kevin",
    "FirstName": "Jimenez",
    "Title": "Sales Representative",
    "HireDate": "2019-01-01T00:00:00.000Z",
    "City": "Springfield",
    "Region": "IL"
}